//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComplyRite.Web.MVC.Areas.SchedulingMgmt.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ScheduleServiceUrls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScheduleServiceUrls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ComplyRite.Web.MVC.Areas.SchedulingMgmt.App_LocalResources.ScheduleServiceUrls", typeof(ScheduleServiceUrls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UserManager/GetAllAuditorsByLocationAndModule.
        /// </summary>
        public static string GetAllAuditorsByLocation {
            get {
                return ResourceManager.GetString("GetAllAuditorsByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Master/GetChecklistForArea?SubAreaCode=.
        /// </summary>
        public static string GetAllChecklistForAreaSubArea {
            get {
                return ResourceManager.GetString("GetAllChecklistForAreaSubArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Master/GetAllChecksByChecklistIDAndSubAreaCode?ChecklistID=.
        /// </summary>
        public static string GetAllChecksByChecklistID {
            get {
                return ResourceManager.GetString("GetAllChecksByChecklistID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UserManager/GetAllCitiesByUUID.
        /// </summary>
        public static string GetAllCitiesByUUID {
            get {
                return ResourceManager.GetString("GetAllCitiesByUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UserManager/GetAllLocationsByCityAndUUID.
        /// </summary>
        public static string GetAllLocationByCityAndUUID {
            get {
                return ResourceManager.GetString("GetAllLocationByCityAndUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserManager/GetAllLocationUserbyManager.
        /// </summary>
        public static string GetAllLocationUserbyManager {
            get {
                return ResourceManager.GetString("GetAllLocationUserbyManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UserManager/GetAllUserAreasandSubAreasbyLocation.
        /// </summary>
        public static string GetAllUserAreasandSubAreasbyLocation {
            get {
                return ResourceManager.GetString("GetAllUserAreasandSubAreasbyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UserManager/GetAllUserAreasbyLocation.
        /// </summary>
        public static string GetAllUserAreasbyLocation {
            get {
                return ResourceManager.GetString("GetAllUserAreasbyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UserManager/GetAllUserSubAreasbyLocation.
        /// </summary>
        public static string GetAllUserSubAreasbyLocation {
            get {
                return ResourceManager.GetString("GetAllUserSubAreasbyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Master/GetChecklistsByAuditID?AuditID=.
        /// </summary>
        public static string GetAuditDetailsbyAuditID {
            get {
                return ResourceManager.GetString("GetAuditDetailsbyAuditID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Master/GetAllChecksByChecklistID?ChecklistID=.
        /// </summary>
        public static string GetChecksByChecklistID {
            get {
                return ResourceManager.GetString("GetChecksByChecklistID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Master/GetCountForPublishedAudits?Fbo=.
        /// </summary>
        public static string GetPublishedAuditCount {
            get {
                return ResourceManager.GetString("GetPublishedAuditCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Master/GetAuditInfo.
        /// </summary>
        public static string GetScheduledAuditsList {
            get {
                return ResourceManager.GetString("GetScheduledAuditsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /UserManager/GetUserDetailsByUUID?UUID=.
        /// </summary>
        public static string GetUserDetailsByUUID {
            get {
                return ResourceManager.GetString("GetUserDetailsByUUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Audit/PublishAudits.
        /// </summary>
        public static string PublishAuditSchedules {
            get {
                return ResourceManager.GetString("PublishAuditSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Master/SaveAuditInfo.
        /// </summary>
        public static string SaveAuditScheduled {
            get {
                return ResourceManager.GetString("SaveAuditScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master/UpdatePublishedAudits.
        /// </summary>
        public static string UpdateAuditScheduled {
            get {
                return ResourceManager.GetString("UpdateAuditScheduled", resourceCulture);
            }
        }
    }
}
