using System.Configuration;
using System.Web;
using System.Web.Mvc;

using Microsoft.AspNet.Identity;
using Microsoft.Owin;
using Microsoft.Owin.Host.SystemWeb;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Cookies;
using Microsoft.Owin.Security.WsFederation;
using Owin;

namespace ComplyRite.Web.MVC
{

    public partial class Startup
    {
        private static string realm = ConfigurationManager.AppSettings["ida:Wtrealm"];
        private static string adfsMetadata = ConfigurationManager.AppSettings["ida:ADFSMetadata"];

        public void ConfigureAuth(IAppBuilder app)
        {
            app.SetDefaultSignInAsAuthenticationType(CookieAuthenticationDefaults.AuthenticationType);

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                //use to manage the authentication Cookie generated by browser 
                CookieManager = new SystemWebCookieManager()
                ,
                AuthenticationType = CookieAuthenticationDefaults.AuthenticationType
            });

            app.UseWsFederationAuthentication(
                new WsFederationAuthenticationOptions
                {
                    Wtrealm = realm,
                    MetadataAddress = adfsMetadata
                });
        }
    }




    //public partial class Startup
    //{
    //    // For more information on configuring authentication, please visit http://go.microsoft.com/fwlink/?LinkId=301864
    //    public void ConfigureAuth(IAppBuilder app)
    //    {
    //        // Enable the application to use a cookie to store information for the signed in user
    //        app.UseCookieAuthentication(new CookieAuthenticationOptions
    //        {
    //            AuthenticationType = DefaultAuthenticationTypes.ApplicationCookie,
    //            LoginPath = new PathString("/Account/Login")
    //        });
    //        // Use a cookie to temporarily store information about a user logging in with a third party login provider
    //        app.UseExternalSignInCookie(DefaultAuthenticationTypes.ExternalCookie);

    //        // Uncomment the following lines to enable logging in with third party login providers
    //        //app.UseMicrosoftAccountAuthentication(
    //        // clientId: "",
    //        // clientSecret: "");

    //        //app.UseTwitterAuthentication(
    //        // consumerKey: "",
    //        // consumerSecret: "");

    //        //app.UseFacebookAuthentication(
    //        // appId: "",
    //        // appSecret: "");

    //        //app.UseGoogleAuthentication();
    //    }
    //}
}